server:
  port: 9003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ceo?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: fewbiuebeot5324980hbhgsd0uub9gpkklnqbp4214989oub926t32be0gbdsn


